const Router = require('express')
const router = new Router()
const itemRouter = require('./itemRouter')
const userRouter = require('./userRouter')
const basketRouter = require('./basketRouter')
const basketItemRouter = require('./basketItemRouter')
const orderRouter = require('./orderRouter')
const orderItemRouter = require('./orderItemRouter')
const infoItemRouter = require('./itemInfoRouter')
const itemColorRouter = require('./itemColorRouter')
const repairRouter = require('./repairRouter')
const dialogRouter = require('./dialogRouter')
const itemTagRouter = require("./itemTagRouter")
const tagToItemRouter = require("./TagToItemRouter")
const requestRouter = require("./requestRouter")

router.use('/user', userRouter)
router.use('/item', itemRouter)
router.use('/basket', basketRouter)
router.use('/basketitem', basketItemRouter)
router.use('/order', orderRouter)
router.use('/orderitem', orderItemRouter)
router.use('/info', infoItemRouter)
router.use('/color', itemColorRouter)
router.use('/repair', repairRouter)
router.use('/dialog', dialogRouter)
router.use('/tag', itemTagRouter)
router.use('/tag-to-item', tagToItemRouter)
router.use('/request', requestRouter)

module.exports = router